<?php

/**
 * @file
 */

/**
 *
 */
function activities_d8_theme($existing, $type, $theme, $path) {
  return [
    'weather_design' => [
      'variables' => [
        'temp' => NULL,
        'pressure' => NULL,
        'humidity' => NULL,
        'temp_min' => NULL,
        'temp_max' => NULL,
      ],
    ],
  ];
}

/**
 *
 */
function activities_d8_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'activities_d8/common-info';
}
